version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: on-failure
    ports:
      - 1234:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
  jenkins-agent-local:
    image: jenkins/ssh-agent:jdk11
    container_name: jenkins-agent-local
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}

volumes:
  jenkins_home:
